### ISSUE TITLE
Modus Penipuan berdasarkan carding. URL https://sponline.vip

### ISSUE THREAD

**Issue by Reno-Sifana** [jovanzers/PhisOff#1]
@jovanzers Saya dapat informasi dari channel telegram sebelah ada modus penipuan. URL: https://sponline.vip di DDoS bisa gak ya? Link Postingan: https://t.me/sihtek/3663

**Comment by jovanzers** [comment]
Ini ya https://splonline.vip? Dibuka cuma redirect ke Google

**Comment by Reno-Sifana** [comment]
> Ini ya https://splonline.vip? Dibuka cuma redirect ke Google

iya. Saya tes barusan di Firefox dah diblokir Google Safe Browsing
![Screenshot from 2023-08-23 08-55-38](https://github.com/jovanzers/PhisOff/assets/68702583/2e4460cd-353d-4fd0-9887-db85acc32f11)

**Comment by jovanzers** [comment]
Coba See details > lanjutkan

**Comment by Reno-Sifana** [comment]
Di laptop setelah klik continue di redirect ke google.com. nyoba lewat HP malah error. ![Screenshot_2023-08-25-21-53-21-947_com.android.chrome.jpg](https://github.com/jovanzers/PhisOff/assets/68702583/36cbe35d-5b5e-45a3-b873-fb0f3119c969)

**Comment by jovanzers** [comment]
Yg di HP typo domainnya, https://splonline.vip

**Comment by Reno-Sifana** [comment]
> Yg di HP typo domainnya, https://splonline.vip

Oh ya benar. ![Screenshot_2023-08-26-09-56-57-497_com.android.chrome.jpg](https://github.com/jovanzers/PhisOff/assets/68702583/58a9f484-8d16-4a3b-828c-bb0fa98f3146)

**Comment by jovanzers** [comment]
Coba lanjutin

**Comment by Reno-Sifana** [comment]
Barusan ngetes di HP android diredirect ke beranda google
